name: Cron Job

on:
  schedule:
    - cron: '0 */12 * * *' # Cada 12 horas
  workflow_dispatch: # Permite ejecución manual

jobs:
  update-csv:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Clonar el Repositorio
    - name: Clonar Repositorio
      uses: actions/checkout@v3

    # Paso 2: Configurar Node.js
    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    # Paso 3: Instalar Dependencias
    - name: Instalar Dependencias
      run: npm install

    # Paso para instalar los navegadores de Playwright
    - name: Instalar Navegadores de Playwright
      run: npx playwright install

    # Paso 4: Ejecutar el Script
    - name: Ejecutar Script
      run: npm run start
      env:
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
        TWILIO_FROM_NUMBER: ${{ secrets.TWILIO_FROM_NUMBER }}
        TWILIO_TO_NUMBER: ${{ secrets.TWILIO_TO_NUMBER }}

    # Paso 5: Commit y Push del Archivo CSV
    - name: Commit y Push del CSV
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add src/csv/
        git diff --cached --exit-code || git commit -m "Actualización automática del archivo CSV"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
